### ISSUE TITLE
Cropped string 

### ISSUE THREAD

**Issue by diorahman** [jhamlet/node-pstrscan#2]
Tried to execute: 

s.scan(/.*$/)

to following string: game::board, game::board:chess, implemented-in::c, interface::x11, role::program, uitoolkit::xlib, use::gameplaying, x11::application 

got

game::board, game::board:chess, implemented-in::c, interface::x11, role::program, uitoolkit::xlib, use::gameplaying, x11::applic

**Comment by jhamlet** [comment]
It looks like you've run afoul of the chunkSize property.

String scanners usually look for discreet, small tokens within strings, and to facilitate faster scanning in PStrScan it tries to fail fast when it searches for a match. See: [PStrScan#chunkSize property](https://github.com/jhamlet/node-pstrscan/blob/master/lib/pstrscan.js#L80) for an explanation.

The constructor takes an "options" object as a second parameter.

Setting a "chunkSize" property higher than the default of 128 characters (or 0 for unlimited) should solve this issue:

``` js
var scanner = new PStrScan(sourceText, { chunkSize: 256 }),
    result = scanner.scan(/.*$/)
;
```

or, you can set it on the instance directly:

``` js
//... after instantiation
scanner.chunkSize = 1028;
var result = scanner.scan(/*.$/);
scanner.chunkSize = 128;
```

Hope that helps,

;-j

**Comment by diorahman** [comment]
Thanks! :-)

**Comment by jhamlet** [comment]
Just thought of a better way:

``` js
var result = scanner.scanUntil(/$/);
```

will return everything from the current point up to the end of the current line (or end of the string), regardless of the chunkSize property setting.
